name: Validate Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: dev

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add custom DNS Mapping
        run: |
          HOST_STRIPPED="${DATABRICKS_HOST#*://}"
          echo "${{ secrets.DATABRICKS_HOST_IP }} $HOST_STRIPPED" | sudo tee -a /etc/hosts

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check Secrets
        run: |
          [ -n "$DATABRICKS_HOST" ] || exit 1
          [ -n "$DATABRICKS_TOKEN" ] || exit 1

      - name: Validate Bundle
        run: databricks bundle validate -t dev

